apiVersion: v1
kind: ConfigMap
metadata:
  name: fastml-serve-config
  namespace: {{NAMESPACE}}
  labels:
    app: fastml-serve
    environment: {{ENVIRONMENT}}
data:
  MODEL_NAME: "distilbert-base-uncased-finetuned-sst-2-english"
  LOG_LEVEL: "INFO"
  MAX_BATCH_SIZE: "32"
  CACHE_SIZE: "1000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastml-serve
  namespace: {{NAMESPACE}}
  labels:
    app: fastml-serve
    component: api
    environment: {{ENVIRONMENT}}
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: fastml-serve
      component: api
  template:
    metadata:
      labels:
        app: fastml-serve
        component: api
        environment: {{ENVIRONMENT}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
      - name: registry-secret
      serviceAccountName: fastml-serve
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
      - name: fastml-serve
        image: {{API_IMAGE}}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: MODEL_NAME
          valueFrom:
            configMapKeyRef:
              name: fastml-serve-config
              key: MODEL_NAME
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: fastml-serve-config
              key: LOG_LEVEL
        - name: MAX_BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: fastml-serve-config
              key: MAX_BATCH_SIZE
        - name: CACHE_SIZE
          valueFrom:
            configMapKeyRef:
              name: fastml-serve-config
              key: CACHE_SIZE
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastml-serve-frontend
  namespace: {{NAMESPACE}}
  labels:
    app: fastml-serve
    component: frontend
    environment: {{ENVIRONMENT}}
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: fastml-serve
      component: frontend
  template:
    metadata:
      labels:
        app: fastml-serve
        component: frontend
        environment: {{ENVIRONMENT}}
    spec:
      imagePullSecrets:
      - name: registry-secret
      serviceAccountName: fastml-serve
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
      - name: frontend
        image: {{FRONTEND_IMAGE}}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: fastml-serve
  namespace: {{NAMESPACE}}
  labels:
    app: fastml-serve
    component: api
    environment: {{ENVIRONMENT}}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: fastml-serve
    component: api

---
apiVersion: v1
kind: Service
metadata:
  name: fastml-serve-frontend
  namespace: {{NAMESPACE}}
  labels:
    app: fastml-serve
    component: frontend
    environment: {{ENVIRONMENT}}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: fastml-serve
    component: frontend

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fastml-serve-hpa
  namespace: {{NAMESPACE}}
  labels:
    app: fastml-serve
    environment: {{ENVIRONMENT}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastml-serve
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60